test new condition

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,9 +42,18 @@ jobs:
         docker tag crypto-tracker "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_SHA::7}"
         docker push "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_SHA::7}"
 
-    - name: Push Docker image on release
-      if: steps.run_tests.outcome == 'success' && github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
+    - name: Test if release tag contains a valid version
+      if: github.event_name == 'release'
       run: |
+        if [[ ! $GITHUB_REF =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Invalid tag format. Please use v{MAJOR}.{MINOR}.{PATCH}"
+          exit 1
+        fi  
+        
+    - name: Build & Push Docker image on release
+      if: steps.run_tests.outcome == 'success' && github.event_name == 'release'
+      run: |
+        docker build -t crypto-tracker .
         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
         docker tag crypto-tracker "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_REF##*/}"
         docker push "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_REF##*/}"
